import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../data/models/booking_models.dart';
import '../../../data/repositories/bookings_repository.dart';
import 'create_request_event.dart';
import 'create_request_state.dart';

class CreateRequestBloc extends Bloc<CreateRequestEvent, CreateRequestState> {
  final BookingsRepository _bookingsRepository;

  CreateRequestBloc({required BookingsRepository bookingsRepository})
      : _bookingsRepository = bookingsRepository,
        super(const CreateRequestState()) {
    on<SelectServiceEvent>(_onSelectService);
    on<RemoveServiceEvent>(_onRemoveService);
    on<ConfirmContactNoticeEvent>(_onConfirmContactNotice);
    on<SelectAppointmentEvent>(_onSelectAppointment);
    on<SelectLocationEvent>(_onSelectLocation);
    on<EnterAgreedPriceEvent>(_onEnterAgreedPrice);
    on<SubmitRequestEvent>(_onSubmitRequest);
  }

  void _onSelectService(SelectServiceEvent event, Emitter<CreateRequestState> emit) {
    final updatedList = List<SelectedServiceModel>.from(state.selectedServices);
    // Check if already selected to prevent duplicates or just update quantity
    final index = updatedList.indexWhere((s) => s.serviceId == event.service.serviceId);
    if (index >= 0) {
      updatedList[index] = event.service;
    } else {
      updatedList.add(event.service);
    }
    emit(state.copyWith(selectedServices: updatedList));
  }

  void _onRemoveService(RemoveServiceEvent event, Emitter<CreateRequestState> emit) {
    final updatedList = List<SelectedServiceModel>.from(state.selectedServices)
      ..removeWhere((s) => s.serviceId == event.serviceId);
    emit(state.copyWith(selectedServices: updatedList));
  }

  void _onConfirmContactNotice(ConfirmContactNoticeEvent event, Emitter<CreateRequestState> emit) {
    emit(state.copyWith(hasConfirmedContact: event.isConfirmed));
  }

  void _onSelectAppointment(SelectAppointmentEvent event, Emitter<CreateRequestState> emit) {
    final appointment = AppointmentModel(
      date: event.date,
      time: event.time,
      timezone: event.timezone,
      timestamp: DateTime.now(), // Real app would construct a proper DateTime from date/time
    );
    emit(state.copyWith(appointment: appointment));
  }

  void _onSelectLocation(SelectLocationEvent event, Emitter<CreateRequestState> emit) {
    emit(state.copyWith(location: event.location));
  }

  void _onEnterAgreedPrice(EnterAgreedPriceEvent event, Emitter<CreateRequestState> emit) {
    final pricing = PricingModel(
      amount: event.amount,
      currency: event.currency,
      priceSource: 'AGREED_IN_CHAT',
    );
    emit(state.copyWith(pricing: pricing));
  }

  Future<void> _onSubmitRequest(SubmitRequestEvent event, Emitter<CreateRequestState> emit) async {
    if (state.selectedServices.isEmpty ||
        !state.hasConfirmedContact ||
        state.appointment == null ||
        state.location == null ||
        state.pricing == null) {
      emit(state.copyWith(errorMessage: 'Please complete all required fields.'));
      return;
    }

    emit(state.copyWith(isSubmitting: true, errorMessage: null));

    try {
      final request = ServiceRequestModel(
        id: '', // Generated by repo
        userId: event.userId,
        providerId: event.providerId,
        status: ServiceRequestStatus.pendingProviderApproval,
        selectedServices: state.selectedServices,
        appointment: state.appointment!,
        location: state.location!,
        pricing: state.pricing!,
        originalRequest: {
          'appointment': state.appointment!.toJson(),
          'location': state.location!.toJson(),
          'pricing': state.pricing!.toJson(),
        },
        revisionNumber: 0,
        lastAction: RequestActionModel(
          type: 'REQUEST_CREATED',
          performedBy: 'USER',
          performedById: event.userId,
          performedAt: DateTime.now(),
        ),
        userConfirmedProviderContact: state.hasConfirmedContact,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final requestId = await _bookingsRepository.createServiceRequest(request);

      emit(state.copyWith(
        isSubmitting: false,
        isSuccess: true,
        newRequestId: requestId,
      ));
    } catch (e) {
      emit(state.copyWith(
        isSubmitting: false,
        errorMessage: 'Failed to submit request: ${e.toString()}',
      ));
    }
  }
}
