// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAHf1YQ7sHAcwlMN8-QiNsT0LF8zS1AVM',
    appId: '1:574849261990:web:352ef92898a6d0edc4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    authDomain: 'naslookapp-ecf15.firebaseapp.com',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
    measurementId: 'G-1CHW6GCDGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2slKpjtRNhbCHDWEO9G5s-z7J9ZG-I4M',
    appId: '1:574849261990:android:c0344be9fd0e0ffdc4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAmReGVYYe7Hlk8NBzZtiqPDR3ABlso8',
    appId: '1:574849261990:ios:b7a1b9a98e9c4d9ac4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
    androidClientId: '574849261990-4iaefgh0imasom85d79dl2i4s1obmkk9.apps.googleusercontent.com',
    iosClientId: '574849261990-s2ih35kf0ljaapltq6d3md1c26vis039.apps.googleusercontent.com',
    iosBundleId: 'com.example.algoharyProject',
  );
}
